cmake_minimum_required(VERSION 3.28)
project(WS10)

set(CMAKE_CXX_STANDARD 17)

add_executable(WS10
        main.cpp
        Car.cpp
        Car.h
        Collection.h
        Employee.cpp
        Employee.h
        ReadWrite.cpp
        ReadWrite.h
        searchNlist.h
        Student.cpp
        Student.h
)
